"""Add seeds variant notes

Revision ID: 8682451f5cbb
Revises: 978c6c6d8e7d
Create Date: 2022-12-12 01:10:18.397202-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8682451f5cbb'
down_revision = '978c6c6d8e7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeds', sa.Column('variant_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seeds', 'variant_notes')
    # ### end Alembic commands ###
