"""Map Plant directly to Cultivar

Revision ID: 5f57ea426e0b
Revises: 8870b41018af
Create Date: 2022-12-15 23:52:50.196272-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f57ea426e0b'
down_revision = '8870b41018af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('plant', sa.Column('cultivar_id', sa.Integer()))
    query = """UPDATE plant p
    SET cultivar_id = s.cultivar_id
    FROM seeds s
    WHERE p.seeds_id = s.id
    """
    op.execute(query)
    op.drop_constraint('_plant_id_uc', 'plant', type_='unique')
    op.create_unique_constraint('_plant_id_uc', 'plant', ['cultivar_id', 'plant_id'])
    op.create_foreign_key(None, 'plant', 'cultivar', ['cultivar_id'], ['id'])
    op.alter_column('plant', 'cultivar_id', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plant', type_='foreignkey')
    op.drop_constraint('_plant_id_uc', 'plant', type_='unique')
    op.create_unique_constraint('_plant_id_uc', 'plant', ['plant_id'])
    op.drop_column('plant', 'cultivar_id')
    # ### end Alembic commands ###
