"""Add plant fields

Revision ID: 8870b41018af
Revises: c8d590c8a4a1
Create Date: 2022-12-14 15:36:42.386414-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8870b41018af'
down_revision = 'c8d590c8a4a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('brix_sg', sa.Numeric(), nullable=True))
    op.add_column('plant', sa.Column('cons', sa.String(), nullable=True))
    op.add_column('plant', sa.Column('died', sa.Date(), nullable=True))
    op.add_column('plant', sa.Column('final_pot_date', sa.Date(), nullable=True))
    op.add_column('plant', sa.Column('flavor_rating', sa.Integer(), nullable=True))
    op.add_column('plant', sa.Column('growth_rating', sa.Integer(), nullable=True))
    op.add_column('plant', sa.Column('health', sa.String(), nullable=True))
    op.add_column('plant', sa.Column('health_rating', sa.Integer(), nullable=True))
    op.add_column('plant', sa.Column('pot_up_date', sa.Date(), nullable=True))
    op.add_column('plant', sa.Column('powdery_mildew', sa.String(length=4), nullable=True))
    op.add_column('plant', sa.Column('pros', sa.String(), nullable=True))
    op.add_column('plant', sa.Column('seeds_collected', sa.Boolean(), nullable=True))
    op.add_column('plant', sa.Column('staked', sa.Boolean(), nullable=True))
    op.add_column('plant', sa.Column('width', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant', 'width')
    op.drop_column('plant', 'staked')
    op.drop_column('plant', 'seeds_collected')
    op.drop_column('plant', 'pros')
    op.drop_column('plant', 'powdery_mildew')
    op.drop_column('plant', 'pot_up_date')
    op.drop_column('plant', 'health_rating')
    op.drop_column('plant', 'health')
    op.drop_column('plant', 'growth_rating')
    op.drop_column('plant', 'flavor_rating')
    op.drop_column('plant', 'final_pot_date')
    op.drop_column('plant', 'died')
    op.drop_column('plant', 'cons')
    op.drop_column('plant', 'brix_sg')
    # ### end Alembic commands ###
